# SPDX-License-Identifier: GPL-2.0

allegro-dvt-objs := allegro-core.o
allegro-dvt-objs += allegro-mail.o
allegro-dvt-objs += allegro-mbox.o
#allegro-dvt-objs += allegro-enc.o
allegro-dvt-objs += allegro-dec.o
allegro-dvt-objs += nal-rbsp.o
allegro-dvt-objs += nal-h264.o
#allegro-dvt-objs += nal-hevc.o

obj-$(CONFIG_VIDEO_ALLEGRO_DVT) += allegro-dvt.o
